# Generated by Django 4.2.3 on 2023-07-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_id', 'movie', 'planet')},
        ),
    ]
